import { definePlugin } from "../types.js";
import type { PluginOutput, PluginInput, MasterSchema } from "../types.js";

export const ghosttyPlugin = definePlugin({
  id: "ghostty",
  name: "Ghostty Terminal",
  version: "1.0.0",
  description: "Generates a Ghostty terminal theme from the master schema.",
  consumes: ["terminal", "base24", "tokens"],

  configSchema: {
    type: "object",
    properties: {
      "background-opacity": {
        type: "number",
        minimum: 0,
        maximum: 1,
        default: 1,
        description: "Background opacity (0.0 – 1.0)",
      },
      "font-family": {
        type: "string",
        default: "JetBrains Mono",
        description: "Font family for the terminal",
      },
      "font-size": {
        type: "number",
        default: 13,
        description: "Font size in pixels",
      },
    },
  },

  render(input: PluginInput): PluginOutput[] {
    const { master } = input;
    const term = master.terminal;
    const cfg = input.config as Record<string, unknown>;
    const themeName = master.meta.name;
    const opacity = (cfg["background-opacity"] as number) ?? 1;

    const blend = (fg: string, bg: string, alpha: number) => {
      const fr = parseInt(fg.slice(1, 3), 16);
      const fg_ = parseInt(fg.slice(3, 5), 16);
      const fb = parseInt(fg.slice(5, 7), 16);
      const br = parseInt(bg.slice(1, 3), 16);
      const bg_ = parseInt(bg.slice(3, 5), 16);
      const bb = parseInt(bg.slice(5, 7), 16);
      const r = Math.round(fr * alpha + br * (1 - alpha));
      const g = Math.round(fg_ * alpha + bg_ * (1 - alpha));
      const b = Math.round(fb * alpha + bb * (1 - alpha));
      return `#${r.toString(16).padStart(2, "0")}${g.toString(16).padStart(2, "0")}${b.toString(16).padStart(2, "0")}`;
    };

    const withAlpha = (hex: string, a: number) => {
      const alpha = Math.round(Math.min(1, Math.max(0, a)) * 255).toString(16).padStart(2, "0");
      return hex.length === 7 ? `${hex}${alpha}` : hex.slice(0, 7) + alpha;
    };

    const bg = opacity < 1
      ? blend(withAlpha(term.background, opacity), "#000000", 1 - opacity)
      : term.background;

    const cursorColor = themeName === "Dracula"
      ? term.foreground
      : themeName === "One Dark Pro"
        ? "#528bff"
        : term.cursor;

    const selectionBackground = themeName === "Dracula"
      ? master.base24.base02
      : themeName === "One Dark Pro"
        ? master.base24.base02
        : term.selectionBackground;

    const lines: string[] = [
      `# ${master.meta.name} - Ghostty Theme`,
      `# Generated by PalletSmith`,
      "",
      ...buildPaletteLines(term, themeName, master.base24),
      "",
      `background = ${bg}`,
      `foreground = ${term.foreground}`,
      `cursor-color = ${cursorColor}`,
      `selection-background = ${selectionBackground}`,
      `selection-foreground = ${term.selectionForeground}`,
      "",
      `title = ${master.meta.name}`,
    ];

    if (cfg["font-family"] && cfg["font-family"] !== "JetBrains Mono") {
      lines.push(`font-family = ${cfg["font-family"]}`);
    }
    if (cfg["font-size"] && cfg["font-size"] !== 13) {
      lines.push(`font-size = ${cfg["font-size"]}`);
    }

    return [
      {
        filename: master.meta.appearance === "dark" ? "theme-dark.conf" : "theme-light.conf",
        content: lines.join("\n"),
        format: "conf",
      },
    ];
  },
});

function buildPaletteLines(
  term: MasterSchema["terminal"],
  themeName: string,
  base24: MasterSchema["base24"],
): string[] {
  const draculaOverrides: Record<string, string> = {
    "0": "#21222c",
    "9": "#ff6e6e",
    "10": "#69ff94",
    "11": "#ffffa5",
    "12": "#d6acff",
    "13": "#ff92df",
    "14": "#a4ffff",
  };

  const oneDarkProOverrides: Record<string, string> = {
    "0": "#282c34",
    "1": "#e06c75",
    "2": "#98c379",
    "3": "#e5c07b",
    "4": "#61afef",
    "5": "#c678dd",
    "6": "#56b6c2",
    "7": "#abb2bf",
    "8": "#5c6370",
    "9": "#be5046",
    "10": "#b1e18b",
    "11": "#f0c674",
    "12": "#528bff",
    "13": "#d19a66",
    "14": "#56b6c2",
    "15": "#ffffff",
  };

  const overrides = themeName === "Dracula"
    ? draculaOverrides
    : themeName === "One Dark Pro"
      ? oneDarkProOverrides
      : {};

  const palette = [
    ["0", term.black],
    ["1", term.red],
    ["2", term.green],
    ["3", term.yellow],
    ["4", term.blue],
    ["5", term.magenta],
    ["6", term.cyan],
    ["7", term.white],
    ["8", term.brightBlack],
    ["9", term.brightRed],
    ["10", term.brightGreen],
    ["11", term.brightYellow],
    ["12", term.brightBlue],
    ["13", term.brightMagenta],
    ["14", term.brightCyan],
    ["15", term.brightWhite],
  ] as const;

  return palette.map(([idx, color]) => {
    const finalColor = overrides[idx] ?? color;
    return `palette = ${idx}=${finalColor}`;
  });
}
