import type { Palette, Appearance, ThemeCustomizations } from "../core/types.js";
import type { PresetPack } from "./index.js";

export const draculaPalette: Palette = {
  bg: "#282A36",
  surface: "#21222C",
  selection: "#44475A",
  border: "#44475A",
  muted: "#6272A4",
  text: "#F8F8F2",
  accent: "#BD93F9",
  red: "#FF5555",
  orange: "#FFB86C",
  yellow: "#F1FA8C",
  green: "#50FA7B",
  cyan: "#8BE9FD",
  blue: "#BD93F9",
  magenta: "#FF79C6",
};

const draculaCustomizations: ThemeCustomizations = {
  plugins: {
    ghostty: {
      cursor: "#F8F8F2",
      selectionBackground: "#44475A",
      palette: {
        "0": "#21222c",
        "9": "#ff6e6e",
        "10": "#69ff94",
        "11": "#ffffa5",
        "12": "#d6acff",
        "13": "#ff92df",
        "14": "#a4ffff",
      },
    },
    zed: {
      style: {
        "background.appearance": "blurred",
        "border": "#3c324bcc",
        "border.variant": "#c9a8f933",
        "border.focused": "#c9a8f977",
        "border.selected": "#c9a8f9bb",
        "border.transparent": "#00000000",
        "elevated_surface.background": "#1e1925ff",
        "surface.background": "#242631ee",
        "background": "#b597e033",
        "element.background": "#1c1d26ff",
        "element.hover": "#3c324bff",
        "element.active": "#796595",
        "element.selected": "#282232",
        "element.disabled": "#e9dbfd",
        "drop_target.background": "#504364",
        "ghost_element.background": "#00000000",
        "ghost_element.hover": "#c9a8f935",
        "ghost_element.active": "#c9a8f950",
        "ghost_element.selected": "#c9a8f925",
        "ghost_element.disabled": "#ff5555ff",
        "text.muted": "#a186c7",
        "text.placeholder": "#C9A8F9",
        "text.disabled": "#C9A8F950",
        "text.accent": "#c9a8f9ff",
        "icon.accent": "#c9a8f9ff",
        "icon.muted": "#F8F8F270",
        "icon.disabled": "#F8F8F240",
        "icon.placeholder": "#F8F8F24F",
        "status_bar.background": "#141119bb",
        "title_bar.background": "#141119bb",
        "title_bar.inactive_background": "#0a080cbb",
        "toolbar.background": "#282a36ff",
        "tab_bar.background": "#282232bb",
        "tab.inactive_background": "#1c1d26ff",
        "tab.active_background": "#282a36ff",
        "search.match_background": "#50fa7b50",
        "panel.background": "#16121b",
        "panel.focused_border": "#c9a8f960",
        "panel.indent_guide": "#F8F8F21F",
        "panel.indent_guide_hover": "#c9a8f935",
        "panel.indent_guide_active": "#C9A8F950",
        "pane.focused_border": "#C9A8F9FF",
        "pane_group.border": "#3c324bcc",
        "scrollbar.thumb.background": "#c9a8f977",
        "scrollbar.thumb.hover_background": "#c9a8f9ff",
        "scrollbar.thumb.active_background": "#c9a8f9ff",
        "scrollbar.thumb.border": "#00000000",
        "scrollbar.track.background": "#141119",
        "scrollbar.track.border": "#c9a8f944",
        "editor.subheader.background": "#1e1925",
        "editor.active_line.background": "#c9a8f933",
        "editor.highlighted_line.background": "#44475a",
        "editor.line_number": "#F8F8F24F",
        "editor.active_line_number": "#C9A8F9",
        "editor.invisible": "#F8F8F230",
        "editor.wrap_guide": "#F8F8F229",
        "editor.active_wrap_guide": "#BD93F966",
        "editor.indent_guide": "#F8F8F21F",
        "editor.indent_guide_active": "#BD93F94F",
        "editor.document_highlight.read_background": "#c9a8f940",
        "editor.document_highlight.write_background": "#44475a",
        "editor.document_highlight.bracket_background": "#bd93f935",
        "terminal.background": "#14151b",
        "terminal.ansi.background": "#14151b",
        "terminal.bright_foreground": "#f9f9f5",
        "terminal.dim_foreground": "#c6c6c2",
        "terminal.ansi.black": "#21222c",
        "terminal.ansi.bright_black": "#919cbf",
        "terminal.ansi.bright_red": "#ff6e6e",
        "terminal.ansi.bright_green": "#69ff94",
        "terminal.ansi.bright_yellow": "#ffffa5",
        "terminal.ansi.blue": "#9580ff",
        "terminal.ansi.bright_blue": "#D6ACFF",
        "terminal.ansi.bright_magenta": "#ff92df",
        "terminal.ansi.bright_cyan": "#a4ffff",
        "terminal.ansi.white": "#F8F8F2",
        "terminal.ansi.bright_white": "#ffffff",
        "link_text.hover": "#8be9fd",
        "conflict": "#dec184",
        "created": "#73fb95ff",
        "deleted": "#ff616e",
        "error": "#e67373ff",
        "error.background": "#242631ee",
        "error.border": "#e67373ff",
        "hidden": "#414754",
        "info": "#73ece5",
        "modified": "#a2edfd",
        "predictive": "#c6c6c2",
        "renamed": "#8be9fd",
        "success": "#79e96dff",
        "unreachable": "#959591",
        "warning": "#e6e373ff",
        "warning.background": "#242631ee",
        "warning.border": "#e6e373ff",
        "ignored": "#F8F8F24F",
      },
      syntax: {
        "string": { color: "#F1FA8C" },
        "number": { color: "#BD93F9" },
        "punctuation": { color: "#FF79C6" },
        "operator": { color: "#FF79C6" },
        "preproc": { color: "#6272A4" },
        "function_": { color: "#50FA7B" },
        "functionBuiltin": { color: "#50FA7B" },
        "functionCall": { color: "#50FA7B" },
        "functionMacro": { color: "#50FA7B" },
        "method": { color: "#50FA7B" },
        "methodCall": { color: "#50FA7B" },
        "type": { color: "#8BE9FD" },
        "typeBuiltin": { color: "#8BE9FD" },
        "typeClass": { color: "#8BE9FD" },
        "typeDefinition": { color: "#8BE9FD" },
        "typeInterface": { color: "#8BE9FD" },
        "typeSuper": { color: "#8BE9FD" },
        "attribute": { color: "#8BE9FD" },
        "property": { color: "#8BE9FD" },
        "variableSpecial": { color: "#BD93F9" },
        "variableParameter": { color: "#FFB86C" },
        "stringRegex": { color: "#FF5555" },
        "commentDoc": { color: "#FF79C6" },
        "constantBuiltin": { color: "#FF79C6" },
        "constantMacro": { color: "#FF79C6" },
        "constructor": { color: "#FF79C6" },
        "stringSpecial": { color: "#FF79C6" },
        "stringSpecialSymbol": { color: "#BD93F9" },
        "tag": { color: "#FF79C6" },
        "emphasis": { color: "#F1FA8C", fontStyle: "italic" },
        "emphasisStrong": { color: "#FFB86C", fontWeight: 700 },
        "enum_": { color: "#BD93F9" },
        "constant": { color: "#BD93F9" },
        "title": { color: "#BD93F9", fontWeight: 600 },
        "variant": { color: "#BD93F9" },
        "boolean": { color: "#FF79C6" },
        "stringEscape": { color: "#FF79C6" },
      },
    },
  },
};

export const draculaPreset: PresetPack = {
  name: "Dracula",
  description: "Dracula — a dark theme with purple accents, popular across editors and terminals.",
  author: "Dracula Team",
  themes: [
    {
      id: "dracula",
      name: "Dracula",
      appearance: "dark" as Appearance,
      palette: draculaPalette,
      customizations: draculaCustomizations,
    },
  ],
};
