import type { Palette, Appearance, ThemeCustomizations } from "../core/types.js";
import type { PresetPack } from "./index.js";

export const oneDarkPalette: Palette = {
  bg: "#282c34",
  surface: "#21252b",
  selection: "#3E4451",
  border: "#3E4451",
  muted: "#5c6370",
  text: "#abb2bf",
  accent: "#61afef",
  red: "#e06c75",
  orange: "#d19a66",
  yellow: "#e5c07b",
  green: "#98c379",
  cyan: "#56b6c2",
  blue: "#61afef",
  magenta: "#c678dd",
};

const oneDarkCustomizations: ThemeCustomizations = {
  plugins: {
    ghostty: {
      cursor: "#528bff",
      selectionBackground: "#3E4451",
      palette: {
        "0": "#282c34",
        "1": "#e06c75",
        "2": "#98c379",
        "3": "#e5c07b",
        "4": "#61afef",
        "5": "#c678dd",
        "6": "#56b6c2",
        "7": "#abb2bf",
        "8": "#5c6370",
        "9": "#be5046",
        "10": "#b1e18b",
        "11": "#f0c674",
        "12": "#528bff",
        "13": "#d19a66",
        "14": "#56b6c2",
        "15": "#ffffff",
      },
    },
    zed: {
      style: {
        "border": "#3e4452",
        "border.variant": "#3e4452",
        "border.focused": "#3e4452",
        "border.selected": "#3e4452",
        "border.transparent": "#3e4452",
        "border.disabled": "#3e4452",
        "elevated_surface.background": "#1e2227",
        "background": "#23272e",
        "element.background": "#404754",
        "element.hover": "#2c313a",
        "element.selected": "#2c313a",
        "ghost_element.hover": "#2c313a",
        "ghost_element.selected": "#2c313a",
        "status_bar.background": "#23272e",
        "title_bar.background": "#23272e",
        "toolbar.background": "#21252b",
        "tab_bar.background": "#1e2227",
        "tab.inactive_background": "#1e2227",
        "tab.active_background": "#23272e",
        "search.match_background": "#d19a6644",
        "panel.background": "#23272e",
        "scrollbar.thumb.background": "#4e566680",
        "scrollbar.thumb.hover_background": "#5a6375",
        "scrollbar.thumb.active_background": "#5a637580",
        "scrollbar.thumb.border": "#4e5666",
        "scrollbar.track.background": "#23272e",
        "editor.active_line.background": "#2c313c",
        "editor.wrap_guide": "#3e4452",
        "editor.indent_guide_active": "#c8c8c859",
        "editor.document_highlight.read_background": "#555a6345",
        "editor.document_highlight.write_background": "#555a6345",
        "terminal.ansi.black": "#3f4451",
        "terminal.ansi.bright_black": "#4f5666",
        "terminal.ansi.red": "#e05561",
        "terminal.ansi.bright_red": "#ff616e",
        "terminal.ansi.green": "#8cc265",
        "terminal.ansi.bright_green": "#a5e075",
        "terminal.ansi.yellow": "#d18f52",
        "terminal.ansi.bright_yellow": "#f0a45d",
        "terminal.ansi.blue": "#4aa5f0",
        "terminal.ansi.bright_blue": "#4dc4ff",
        "terminal.ansi.magenta": "#c162de",
        "terminal.ansi.bright_magenta": "#de73ff",
        "terminal.ansi.cyan": "#42b3c2",
        "terminal.ansi.bright_cyan": "#4cd1e0",
        "terminal.ansi.white": "#d7dae0",
        "terminal.ansi.bright_white": "#e6e6e6",
        "created": "#a5e075",
        "deleted": "#ff616e",
        "error": "#c24038",
        "error.background": "#1e2227",
        "error.border": "#a03237",
        "hint": "#7a849c",
        "ignored": "#636b78",
        "info": "#61afef",
        "info.background": "#1e2227",
        "modified": "#e5c07b",
        "predictive": "#4D5970",
        "warning": "#d19a66",
        "warning.background": "#1e2227",
        "warning.border": "#89734d",
      },
      syntax: {
        "comment": { color: "#7f838c" },
        "variable": { color: "#e06c75" },
        "variableBuiltin": { color: "#e06c75" },
        "variableMember": { color: "#e06c75" },
        "variableSpecial": { color: "#e5c07b" },
        "property": { color: "#e06c75" },
        "tag": { color: "#e06c75" },
        "constructor": { color: "#e06c75" },
        "stringRegex": { color: "#e06c75" },
        "stringSpecial": { color: "#e06c75" },
        "stringSpecialSymbol": { color: "#e06c75" },
        "keyword": { color: "#c678dd" },
        "keywordOperator": { color: "#c678dd" },
        "emphasis": { color: "#c678dd" },
        "type": { color: "#e5c07b" },
        "title": { color: "#d07277ff" },
        "punctuation": { color: "#abb2bf" },
        "punctuationBracket": { color: "#abb2bf" },
        "punctuationDelimiter": { color: "#abb2bf" },
        "punctuationSpecial": { color: "#abb2bf" },
        "operator": { color: "#abb2bf" },
        "punctuationListMarker": { color: "#d07277ff" },
        "variant": { color: "#61afef" },
        "linkText": { color: "#61afef" },
        "linkUri": { color: "#61afef" },
        "enum_": { color: "#56b6c2" },
        "attribute": { color: "#d19a66" },
        "commentDoc": { color: "#7f838c" },
      },
    },
  },
};

export const oneDarkPreset: PresetPack = {
  name: "One Dark Pro",
  description: "One Dark Pro — a dark theme inspired by Atom's One Dark, popular across editors.",
  author: "binaryify",
  themes: [
    {
      id: "onedark",
      name: "One Dark Pro",
      appearance: "dark" as Appearance,
      palette: oneDarkPalette,
      customizations: oneDarkCustomizations,
    },
  ],
};
