import { definePlugin } from "./types.js";
import type { PluginOutput, PluginInput } from "./types.js";
import { withAlpha, blend } from "../core/color.js";

export const ghosttyPlugin = definePlugin({
  id: "ghostty",
  name: "Ghostty Terminal",
  version: "1.0.0",
  description: "Generates a Ghostty terminal theme from the master schema.",
  consumes: ["terminal", "base24", "tokens"],

  configSchema: {
    type: "object",
    properties: {
      "background-opacity": {
        type: "number",
        minimum: 0,
        maximum: 1,
        default: 1,
        description: "Background opacity (0.0 – 1.0)",
      },
      "font-family": {
        type: "string",
        default: "JetBrains Mono",
        description: "Font family for the terminal",
      },
      "font-size": {
        type: "number",
        default: 13,
        description: "Font size in pixels",
      },
    },
  },

  render(input: PluginInput): PluginOutput[] {
    const { master } = input;
    const term = master.terminal;
    const cfg = input.config as Record<string, unknown>;
    const opacity = (cfg["background-opacity"] as number) ?? 1;

    const bg = opacity < 1
      ? blend(withAlpha(term.background, opacity), "#000000", 1 - opacity)
      : term.background;

    const lines: string[] = [
      `# ${master.meta.name} - Ghostty Theme`,
      `# Generated by ThemeSmith`,
      "",
      ...buildPaletteLines(term),
      "",
      `background = ${bg}`,
      `foreground = ${term.foreground}`,
      `cursor-color = ${term.cursor}`,
      `selection-background = ${term.selectionBackground}`,
      `selection-foreground = ${term.selectionForeground}`,
      "",
      `title = ${master.meta.name}`,
    ];

    // Conditionally add font settings if non-default
    if (cfg["font-family"] && cfg["font-family"] !== "JetBrains Mono") {
      lines.push(`font-family = ${cfg["font-family"]}`);
    }
    if (cfg["font-size"] && cfg["font-size"] !== 13) {
      lines.push(`font-size = ${cfg["font-size"]}`);
    }

    return [
      {
        filename: master.meta.appearance === "dark" ? "theme-dark" : "theme-light",
        content: lines.join("\n"),
        format: "conf",
      },
    ];
  },
});

function buildPaletteLines(term: import("../core/types.js").TerminalPalette): string[] {
  const palette = [
    ["0", term.black],
    ["1", term.red],
    ["2", term.green],
    ["3", term.yellow],
    ["4", term.blue],
    ["5", term.magenta],
    ["6", term.cyan],
    ["7", term.white],
    ["8", term.brightBlack],
    ["9", term.brightRed],
    ["10", term.brightGreen],
    ["11", term.brightYellow],
    ["12", term.brightBlue],
    ["13", term.brightMagenta],
    ["14", term.brightCyan],
    ["15", term.brightWhite],
  ] as const;

  return palette.map(([idx, color]) => `palette = ${idx}=${color}`);
}
