import { definePlugin } from "./types.js";
import type { PluginOutput, PluginInput } from "./types.js";
import type { MasterSchema } from "../core/types.js";
import { withAlpha, blend, lighten, darken } from "../core/color.js";

export const openchamberPlugin = definePlugin({
  id: "openchamber",
  name: "OpenChamber",
  version: "1.0.0",
  description: "Generates an OpenChamber theme JSON file from the master schema.",
  consumes: ["tokens", "syntax", "status", "base24"],

  render(input: PluginInput): PluginOutput[] {
    const { master } = input;
    const t = master.tokens;
    const s = master.syntax;
    const status = master.status;
    const base24 = master.base24;
    const appearance = master.meta.appearance;
    const isDark = appearance === "dark";

    const accent = master.meta.basePalette.accent;

    const theme = {
      metadata: {
        id: `theme-${appearance}`,
        name: `${master.meta.name} ${appearance === "dark" ? "Dark" : "Light"}`,
        description: `Generated by ThemeSmith for ${master.meta.author}`,
        version: master.meta.version,
        variant: appearance,
        tags: [appearance, "generated", "themesmith"],
      },
      colors: {
        primary: {
          base: accent,
          hover: isDark ? lighten(accent, 8) : darken(accent, 8),
          active: isDark ? darken(accent, 5) : lighten(accent, 5),
          foreground: t.background,
          muted: withAlpha(accent, 0.5),
          emphasis: isDark ? lighten(accent, 10) : darken(accent, 10),
        },
        surface: {
          background: t.background,
          foreground: t.textPrimary,
          muted: withAlpha(t.surface, 0.56),
          mutedForeground: t.textMuted,
          elevated: withAlpha(t.elevatedSurface, 0.56),
          elevatedForeground: t.textPrimary,
          overlay: withAlpha(t.overlay, 0.5),
          subtle: t.surface,
        },
        interactive: {
          border: t.border,
          borderHover: t.hoverBackground,
          borderFocus: t.borderFocused,
          selection: t.selectionBackground,
          selectionForeground: t.textPrimary,
          focus: t.focusRing,
          focusRing: withAlpha(t.focusRing, 0.31),
          cursor: t.textAccent,
          hover: withAlpha(t.textPrimary, 0.06),
          active: withAlpha(t.textPrimary, 0.12),
        },
        status: {
          error: status.error,
          errorForeground: t.background,
          errorBackground: withAlpha(status.error, 0.12),
          errorBorder: withAlpha(status.error, 0.31),
          warning: status.warning,
          warningForeground: t.background,
          warningBackground: withAlpha(status.warning, 0.12),
          warningBorder: withAlpha(status.warning, 0.31),
          success: status.success,
          successForeground: t.background,
          successBackground: withAlpha(status.success, 0.12),
          successBorder: withAlpha(status.success, 0.31),
          info: status.info,
          infoForeground: t.background,
          infoBackground: withAlpha(status.info, 0.12),
          infoBorder: withAlpha(status.info, 0.31),
        },
        pr: {
          open: t.textAccent,
          draft: t.textMuted,
          blocked: status.warning,
          merged: t.cyan,
          closed: status.error,
        },
        syntax: {
          base: {
            background: t.editorBackground,
            foreground: t.editorForeground,
            comment: s.comment?.color ?? t.textMuted,
            keyword: s.keyword?.color ?? t.textAccent,
            string: s.string?.color ?? t.textPrimary,
            number: s.number?.color ?? t.textPrimary,
            function: s.function_?.color ?? t.textPrimary,
            variable: s.variable?.color ?? t.textPrimary,
            type: s.type?.color ?? t.textPrimary,
            operator: s.operator?.color ?? t.textMuted,
          },
          tokens: {
            commentDoc: s.commentDoc?.color,
            stringEscape: s.stringEscape?.color,
            keywordImport: s.keywordImport?.color,
            storageModifier: s.keywordType?.color,
            functionCall: s.functionCall?.color,
            method: s.method?.color,
            variableProperty: s.property?.color,
            variableOther: s.variableSpecial?.color,
            variableGlobal: s.namespace?.color,
            variableLocal: s.variable?.color,
            parameter: s.parameter?.color,
            constant: s.constant?.color,
            class: s.typeClass?.color,
            className: s.type?.color,
            interface: s.typeInterface?.color,
            struct: s.type?.color,
            enum: s.enum_?.color,
            typeParameter: s.type?.color,
            namespace: s.namespace?.color,
            module: s.module?.color,
            tag: s.tag?.color,
            jsxTag: s.tag?.color,
            tagAttribute: s.tagAttribute?.color,
            tagAttributeValue: s.string?.color,
            boolean: s.boolean?.color,
            decorator: s.functionDecorator?.color,
            label: s.label?.color,
            punctuation: s.punctuation?.color,
            macro: s.functionMacro?.color,
            preprocessor: s.preproc?.color,
            regex: s.stringRegex?.color,
            url: s.stringSpecialUrl?.color,
            key: s.attribute?.color,
            exception: s.keywordException?.color,
          },
          highlights: {
            diffAdded: s.diffPlus?.color,
            diffAddedBackground: withAlpha(s.diffPlus?.color ?? t.textAccent, 0.12),
            diffRemoved: s.diffMinus?.color,
            diffRemovedBackground: withAlpha(s.diffMinus?.color ?? status.error, 0.12),
            diffModified: status.info,
            diffModifiedBackground: withAlpha(status.info, 0.12),
            lineNumber: t.editorLineNumber,
            lineNumberActive: t.editorActiveLineNumber,
          },
        },
        markdown: {
          heading1: t.textPrimary,
          heading2: t.textPrimary,
          heading3: t.textPrimary,
          heading4: t.textPrimary,
          link: t.linkForeground,
          linkHover: t.linkHoverForeground,
          inlineCode: s.string?.color ?? t.textAccent,
          inlineCodeBackground: t.surface,
          blockquote: t.textMuted,
          blockquoteBorder: t.border,
          listMarker: s.keyword?.color ?? t.textAccent,
        },
        chat: {
          userMessage: t.textPrimary,
          userMessageBackground: blend(t.textAccent, t.background, 0.12),
          assistantMessage: t.textPrimary,
          assistantMessageBackground: t.background,
          timestamp: t.textMuted,
          divider: t.border,
        },
        tools: {
          background: withAlpha(t.surface, 0.31),
          border: withAlpha(t.border, 0.61),
          headerHover: withAlpha(t.border, 0.31),
          icon: t.iconMuted,
          title: t.textPrimary,
          description: t.textMuted,
          edit: {
            added: s.diffPlus?.color ?? t.textAccent,
            addedBackground: withAlpha(s.diffPlus?.color ?? t.textAccent, 0.14),
            removed: s.diffMinus?.color ?? status.error,
            removedBackground: withAlpha(s.diffMinus?.color ?? status.error, 0.14),
            lineNumber: t.editorLineNumber,
          },
        },
      },
      config: {
        fonts: {
          sans: '"SF Mono", "Fira Code", monospace',
          mono: '"SF Mono", "Fira Code", monospace',
          heading: '"SF Mono", "Fira Code", monospace',
        },
        radius: {
          none: "0",
          sm: "0.25rem",
          md: "0.5rem",
          lg: "0.75rem",
          xl: "1rem",
          full: "9999px",
        },
        transitions: {
          fast: "150ms ease",
          normal: "250ms ease",
          slow: "350ms ease",
        },
      },
    };

    return [
      {
        filename: `theme-${appearance}.json`,
        content: JSON.stringify(theme, null, 2),
        format: "json",
      },
    ];
  },
});
